In [2]:
import numpy as np

In [3]:
array = np.array([1, 2, 3, 4, 5, 6])
array

array([1, 2, 3, 4, 5, 6])

In [4]:
arrays_dividido = np.split(array, 3)
arrays_dividido

[array([1, 2]), array([3, 4]), array([5, 6])]

In [5]:
for i, value in enumerate(arrays_dividido):
    print(f'Parte {i+1}-> {value}')

Parte 1-> [1 2]
Parte 2-> [3 4]
Parte 3-> [5 6]


In [15]:
#Criando um arry 1D com temperaturas diárias de um mês (30 dias)
temperaturas = np.array([22, 21, 23, 25, 20, 19, 21,
                        24, 26, 27, 25, 22,
                        20, 18, 19, 20, 21,
                        22, 23, 24, 25, 26,
                        27, 28, 29, 30, 29,
                        28, 27, 26, 26, 24])
print(temperaturas.__len__())
print(temperaturas)

32
[22 21 23 25 20 19 21 24 26 27 25 22 20 18 19 20 21 22 23 24 25 26 27 28
 29 30 29 28 27 26 26 24]


In [17]:
semanas = np.split(temperaturas, 4)
semanas

[array([22, 21, 23, 25, 20, 19, 21, 24]),
 array([26, 27, 25, 22, 20, 18, 19, 20]),
 array([21, 22, 23, 24, 25, 26, 27, 28]),
 array([29, 30, 29, 28, 27, 26, 26, 24])]

In [18]:
for i, value in enumerate(semanas):
    print(f'Semana {i+1}: {value}')

Semana 1: [22 21 23 25 20 19 21 24]
Semana 2: [26 27 25 22 20 18 19 20]
Semana 3: [21 22 23 24 25 26 27 28]
Semana 4: [29 30 29 28 27 26 26 24]


In [19]:
medias_semanas = [np.mean(semana) for semana in semanas]
medias_semanas

[np.float64(21.875), np.float64(22.125), np.float64(24.5), np.float64(27.375)]

In [23]:
for i, value in enumerate(medias_semanas):
    print(f'Media semana {i+1} ; {value:.2f} ºC')

Media semana 1 ; 21.88 ºC
Media semana 2 ; 22.12 ºC
Media semana 3 ; 24.50 ºC
Media semana 4 ; 27.38 ºC
