In [1]:
import numpy as np

In [3]:
# Criando os dados
nomes = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eva'])
notas_matematica = np.array([55, 67, 72, 48, 90])
notas_fisica = np.array([88, 76, 95, 64, 70])

In [7]:
# Calculando a média das notas
media = np.mean(np.column_stack((notas_matematica, notas_fisica)), axis= 1)
media

array([71.5, 71.5, 83.5, 56. , 80. ])

In [ ]:
# Identificando alunos aprovados
alunos_aprovados = np.where(media > 60)
alunos_aprovados

(array([0, 1, 2, 4]),)

In [10]:
# exibindo os alunos aprovados
media[alunos_aprovados]

array([71.5, 71.5, 83.5, 80. ])

In [12]:
# Organizando os dados em uma unica tabela
dados_tabela = np.column_stack((nomes, notas_matematica, notas_fisica, media))
dados_tabela

array([['Alice', '55', '88', '71.5'],
       ['Bob', '67', '76', '71.5'],
       ['Charlie', '72', '95', '83.5'],
       ['David', '48', '64', '56.0'],
       ['Eva', '90', '70', '80.0']], dtype='<U32')

In [ ]:
# Exibindo alunos aprovados
for i in alunos_aprovados[0]:
    print(f'{dados_tabela[i][0]} - Média: {media[i]:.2f}')

Alice - Média: 71.50
Bob - Média: 71.50
Charlie - Média: 83.50
Eva - Média: 80.00


In [14]:
# Dividindo alunos em grupos
grupos = np.array_split(nomes, 3)

for i, value in enumerate(grupos):
    print(f'Grupo {i+1}: {value}')

Grupo 1: ['Alice' 'Bob']
Grupo 2: ['Charlie' 'David']
Grupo 3: ['Eva']
