In [ ]:
import numpy as np

In [2]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [3]:
# Adição com o NUMPY
soma = np.add(array, 10)
soma

array([11, 12, 13, 14, 15])

In [4]:
# Subtração com NUMPY
subtracao = np.subtract(array, 5)
subtracao

array([-4, -3, -2, -1,  0])

In [5]:
# Multiplicação com NUMPY
produto = np.multiply(array, 2)
produto

array([ 2,  4,  6,  8, 10])

In [6]:
# Divisao com NUMPY
divisao = np.divide(array, 2)
divisao

array([0.5, 1. , 1.5, 2. , 2.5])

In [7]:
# Funções Trigonométricas
seno = np.sin(array)
print(seno)

cosseno = np.cos(array)
print(cosseno)


[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [9]:
# Funções Estatísticas
media = np.mean(array)
print(media)

desvio_padrao = np.std(array)
print(desvio_padrao)

3.0
1.4142135623730951


In [10]:
# Funções de comparação
comparacao_maior_que_3 = array > 3
comparacao_maior_que_3

array([False, False, False,  True,  True])

In [11]:
# Combinando Funções
resultado = np.sqrt(array) + np.power(array, 2)
resultado

array([ 2.        ,  5.41421356, 10.73205081, 18.        , 27.23606798])

In [12]:
# Funções Exponencias
exponencial = np.exp(array)
exponencial

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [13]:
# Função de Logaritmo
logaritmo = np.log(array)
logaritmo

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [14]:
# Função de Arredondamento
arredondado = np.round(array / 2)
arredondado

array([0., 1., 2., 2., 2.])

In [15]:
# Função de Potência
potencia = np.power(array, 3)
potencia

array([  1,   8,  27,  64, 125])