**Copy**
- Uma nova cópia do array é criada em memória. Isso significa que as 2 matrizes (original e cópia) são independentes uma da outra.

**View**
- Não é criada uma nova cópia na memória. A view compartilha os mesmos dados que o array original

In [3]:
import numpy as np

In [4]:
array_original = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])
array_original

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# Cópia Rasa (View)
array_view = array_original[1: , 1:]
array_view

array([[5, 6],
       [8, 9]])

In [ ]:
# Alterando o array_view
array_view[0,0] = 99
array_view

array([[99,  6],
       [ 8,  9]])

In [9]:
# Alteração reflete direto no array_original
array_original

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [10]:
# Cópia Profunda (Copy)
array_copia = array_original.copy()
array_copia

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [ ]:
# Alterando um valor do array copiado
array_copia[0,0] = 222
array_copia

array([[222,   2,   3],
       [  4,  99,   6],
       [  7,   8,   9]])

In [13]:
# A mudança não reflete no array_original
array_original

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])